### ISSUE TITLE
Common - Scrolling text blocks tap actions

### ISSUE THREAD

**Issue by mobify-derrick** [mobify/pinny#12]
Device: Common
OS: Common

Steps:
1. Open examples page
2. Open a pinny modal
3. Scroll the text
4. While text is scrolling tap the "X"

Results:
iOS - text continues to scroll, modal closes once scrolling complete
Android - scroll stops once "X" is tapped, pinny remains open
Windows Phone - scroll stops once "X" is tapped, pinny remains open and "X" remains highlighted

Expected:
Pinny should close right when "X" is tapped

**Comment by scalvert** [comment]
Closing as an edge case.
