### ISSUE TITLE
Form input hidden beneath keyboard on Android 4.4.2

### ISSUE THREAD

**Issue by jeffkamo** [mobify/pinny#81]
Focusing on an input that's close to the bottom of a pinny modal opens the Android keyboard. However, the keyboard covers the input and while the keyboard is open it is impossible to scroll the input into view.

Example of a pinny whose "forgot password" input field is close to the bottom of the modal. This is after focusing on the input:

![screenshot_2015-03-30-17-09-42](https://cloud.githubusercontent.com/assets/734535/6955220/81c57392-d88f-11e4-90bf-26d19708cf5c.jpg)

**Comment by jeffkamo** [comment]
Issue doesn't occur in Pinny examples. Might be project specific. Closing for now.

**Comment by scalvert** [comment]
Just to follow up on this, we add a spacer at the bottom of the pinny content when it opens to accommodate this issue. It adds a large space at the bottom which allows for scrolling to the input.
