### ISSUE TITLE
Dependencies need to be updated

### ISSUE THREAD

**Issue by dennislzf** [mobify/pinny#85]
In adaptivejs/assets/js/config.. If you add pinny you must also add these 3 packages in addition to those already listed in readme

 'event-polyfill': '../../../bower_components/pinny/src/js/utils/event-polyfil',
        'velocity': '../../../bower_components/mobify-velocity/velocity.min',
        'isChildOf': '../../../bower_components/selector-utils/src/selector/isChildOf',

@tedtate

**Comment by vmarta** [comment]
:+1: Yess, I came across this issue in the readme today. The example's config is actually more correct than the one listed in the readme.
