### ISSUE TITLE
Readme does not mention that `coverage` option also accepts px value

### ISSUE THREAD

**Issue by vmarta** [mobify/pinny#88]
There are cases when you prefer to use absolute distance instead of the relative %. And pinny actually supports px value too!

**Comment by ericmuyser** [comment]
An issue for a readme? Wouldn't it be quicker to update it yourself?

**Comment by vmarta** [comment]
Not for me :) This issue is like a todo/reminder for me.

**Comment by donnielrt** [comment]
@vmarta good find! I'm not sure if we actually want to encourage this, however, since we want people to think more responsive (%ages instead of pxs). Does that make sense?
