### ISSUE TITLE
Velocity jQuery file doesn't exist

### ISSUE THREAD

**Issue by cole-sanderson** [mobify/pinny#90]
In README, it says if you are using jQuery and will need to use 'bower_components/velocity/jquery.velocity.js' but this file does not exist. 

You can see in Mobify Velocity repo here: https://github.com/mobify/velocity

Original Velocity repo here: https://github.com/julianshapiro/velocity

There is no jquery.velocity.js file in both repos.

**Comment by donnielrt** [comment]
Thanks for bringing this up Cole, we'll review this and update Readme if needed.
